### ISSUE TITLE
Replace Favorites Button 

### ISSUE THREAD

**Issue by jzukosky** [TigerHacks/app-ios#17]
The Favorite Button for prizes is currently toggling between "Favorite" and "Unfavorite." I would much prefer if this were an image, as it would be less space intensive and would look better. 

Current thought I'm having is a heart/start going from an outline to filled in. Could be animated if you want to make a project of it, but ultimately unnecessary. Feel free to be creative with it.

**Comment by okrek6** [comment]
Awaiting Pull Requests
