### ISSUE TITLE
Make Sponsor Collection View not Trash

### ISSUE THREAD

**Issue by jzukosky** [TigerHacks/app-ios#24]
It currently looks bad, somebody fix it

**Comment by eteters** [comment]
![image](https://user-images.githubusercontent.com/17036113/45308946-3e927c80-b4e8-11e8-8c37-792b1053badf.png)

Steps in the right direction?

**Comment by eteters** [comment]
I'm thinking maybe the borders could be circles. Or instead of borders each one could be sitting on a solid line. Or maybe the borders need to be thicker and darker. One problem is that it isn't immediately apparent they are clickable, I think

**Comment by jzukosky** [comment]
I'm digging the change, definitely in the right direction. Maybe a really subtle drop shadow could help with knowing its clickable?

**Comment by eteters** [comment]
Ah yeah good idea lemme see

**Comment by eteters** [comment]
![image](https://user-images.githubusercontent.com/17036113/45379870-e7afa480-b5c6-11e8-9d90-18b767e23fa8.png)
Shadows are good

**Comment by jzukosky** [comment]
Definitely looks much better. Will look even better when we get actual logo images
