### ISSUE TITLE
Find Other Resources for the Resources section

### ISSUE THREAD

**Issue by jzukosky** [TigerHacks/app-ios#3]
Besides TigerTalks, we need to fill out the resources section with more items. Anything you think would be interesting is a good suggestion, tutorials, videos, books, examples, etc.

**Comment by jzukosky** [comment]
Feel free to leave any links as comments here

**Comment by okrek6** [comment]
We should put the GitHub PDF from Dale's course up there.

**Comment by okrek6** [comment]
Swift 4.1 and then eventually 4.2 Developer Guide
