### ISSUE TITLE
Change Back buttons to be more descriptive

### ISSUE THREAD

**Issue by jzukosky** [TigerHacks/app-ios#6]
The back buttons for map events and the schedule currently just read "back" when they should read "Map" and "Schedule" respectively. Look to the prizes and sponsors tabs for an example of the functionality

**Comment by nathanb95** [comment]
Created a branch with a solution for this

**Comment by jzukosky** [comment]
Awesome, go ahead and create a pull request with that branch, add everyone as a reviewer, and we'll look it over, approve it, and merge it in.

**Comment by jzukosky** [comment]
@nathanb95 idk if it sends a notification when I respond so tagging just in case
