### ISSUE TITLE
Add Loading symbol for TigerTalks

### ISSUE THREAD

**Issue by jzukosky** [TigerHacks/app-ios#7]
Currently when the user opens a TigerTalk, it takes a second to load the video from youtube. There should be a UIActivityIndicator that lets the user know that it's loading. Currently its blank

**Comment by nathanb95** [comment]
Added a branch with a rough implementation of the Activity Indicator, let me know how that looks

**Comment by jzukosky** [comment]
Go ahead and just create a PR, so we can look at it there
