### ISSUE TITLE
Fix Time in schedule rounding to the hour

### ISSUE THREAD

**Issue by eteters** [TigerHacks/app-ios#79]
When I set the Api to any time that is not on the hour, the app thinks we just want hour. 

Ex. Event at 11:59 -> app says 11:00

I don't know why yet

**Comment by jzukosky** [comment]
No idea why this is happening. 

Here is my code for formatting and retrieving the date. 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/23271436/47052015-4dfe8880-d16c-11e8-99b4-aa7115614dd5.png">

I printed the JSON out and the minutes are correct, but when I print the actual event out after loading it in, the date is wrong.

**Comment by nathanb95** [comment]
Is it because there is no .minute for the dateComponents?

**Comment by jzukosky** [comment]
Looks like that's it. Nice catch Nathan!
